const sampleListings = {
  data: [
    // --- TRENDING ---
    {
      title: "Royal Heritage Haveli",
      desc: "Experience the royal lifestyle in this restored 19th-century haveli. Enjoy traditional Rajasthani cuisine and folk music under the stars.",
      img: {
        filename: "heritage_haveli",
        url: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=60",
      },
      price: 4500,
      location: "Jaipur, Rajasthan",
      country: "India",
      category: "Trending",
      geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
    },
    {
      title: "Luxury Loft in UB City",
      desc: "Stay in the heart of Bangalore's most upscale district. Walking distance to the best pubs and Cubbon Park.",
      img: {
        filename: "bangalore_loft",
        url: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=60",
      },
      price: 5500,
      location: "Bangalore, Karnataka",
      country: "India",
      category: "Trending",
      geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    },
    {
      title: "Goan Beach Villa",
      desc: "Steps away from the golden sands, this villa captures the vibrant spirit of Goa. Relax with a drink and listen to the waves.",
      img: {
        filename: "goa_villa",
        url: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=60",
      },
      price: 5000,
      location: "Calangute, Goa",
      country: "India",
      category: "Trending",
      geometry: { type: "Point", coordinates: [73.7556, 15.5494] },
    },
    {
      title: "Lake View Palace",
      desc: "Live like a Maharaja in this stunning palace hotel in the city of lakes. Offers breathtaking sunset views.",
      img: {
        filename: "udaipur_palace",
        url: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=60",
      },
      price: 7000,
      location: "Udaipur, Rajasthan",
      country: "India",
      category: "Trending",
      geometry: { type: "Point", coordinates: [73.6828, 24.5854] },
    },

    // --- ROOMS ---
    {
      title: "Cozy Room in Hauz Khas",
      desc: "A private room in a vibrant neighborhood known for its medieval history and trendy cafes.",
      img: {
        filename: "delhi_room",
        url: "https://images.unsplash.com/photo-1522771753035-484989f5f817?auto=format&fit=crop&w=800&q=60",
      },
      price: 1200,
      location: "New Delhi, Delhi",
      country: "India",
      category: "Rooms",
      geometry: { type: "Point", coordinates: [77.1906, 28.5494] },
    },
    {
      title: "Modern Studio in Bandra",
      desc: "Compact yet stylish studio in the queen of suburbs. Perfect for solo travelers or couples.",
      img: {
        filename: "mumbai_studio",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
      },
      price: 2500,
      location: "Mumbai, Maharashtra",
      country: "India",
      category: "Rooms",
      geometry: { type: "Point", coordinates: [72.8347, 19.0596] },
    },
    {
      title: "Heritage Room in Fort Kochi",
      desc: "Stay in a Portuguese-style heritage home with a private balcony overlooking the street.",
      img: {
        filename: "kochi_room",
        url: "https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?auto=format&fit=crop&w=800&q=60",
      },
      price: 1800,
      location: "Kochi, Kerala",
      country: "India",
      category: "Rooms",
      geometry: { type: "Point", coordinates: [76.2396, 9.9647] },
    },
    {
      title: "Eco-Bamboo Hut Room",
      desc: "A sustainable stay experience in the bamboo forests of the Northeast. Ideal for nature lovers.",
      img: {
        filename: "guwahati_hut",
        url: "https://images.unsplash.com/photo-1534947926173-776369c0d3a7?auto=format&fit=crop&w=800&q=60",
      },
      price: 1200,
      location: "Guwahati, Assam",
      country: "India",
      category: "Rooms",
      geometry: { type: "Point", coordinates: [91.7362, 26.1158] },
    },

    // --- ICONIC CITIES ---
    {
      title: "Ghat View Guest House",
      desc: "Overlooking the sacred Ganges, this heritage guest house offers a spiritual and cultural experience like no other.",
      img: {
        filename: "varanasi_ghat",
        url: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=60",
      },
      price: 1500,
      location: "Varanasi, Uttar Pradesh",
      country: "India",
      category: "Iconic Cities",
      geometry: { type: "Point", coordinates: [83.0076, 25.3176] },
    },
    {
      title: "Urban Loft in Mumbai",
      desc: "A modern loft in the heart of the city that never sleeps. Close to Marine Drive and vibrant nightlife.",
      img: {
        filename: "mumbai_loft",
        url: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=800&q=60",
      },
      price: 6000,
      location: "Mumbai, Maharashtra",
      country: "India",
      category: "Iconic Cities",
      geometry: { type: "Point", coordinates: [72.8777, 19.076] },
    },
    {
      title: "French Colonial Villa",
      desc: "Experience the French charm in India. This yellow colonial villa is located in the quiet streets of White Town.",
      img: {
        filename: "pondicherry_villa",
        url: "https://images.unsplash.com/photo-1582645745122-8a796289648d?auto=format&fit=crop&w=800&q=60",
      },
      price: 3000,
      location: "Puducherry",
      country: "India",
      category: "Iconic Cities",
      geometry: { type: "Point", coordinates: [79.8083, 11.9416] },
    },
    {
      title: "Colonial Suite in Kolkata",
      desc: "Stay in a British-era mansion near Park Street. High ceilings, vintage furniture, and classic Bengali hospitality.",
      img: {
        filename: "kolkata_colonial",
        url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=60",
      },
      price: 2800,
      location: "Kolkata, West Bengal",
      country: "India",
      category: "Iconic Cities",
      geometry: { type: "Point", coordinates: [88.3639, 22.5726] },
    },

    // --- MOUNTAINS ---
    {
      title: "Mountain View Cottage",
      desc: "Nestled in the Himalayas, this cozy cottage offers panoramic views of snow-capped peaks. Perfect for a peaceful retreat.",
      img: {
        filename: "manali_cottage",
        url: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=60",
      },
      price: 2800,
      location: "Manali, Himachal Pradesh",
      country: "India",
      category: "Mountains",
      geometry: { type: "Point", coordinates: [77.1892, 32.2396] },
    },
    {
      title: "Shillong Cloud Cottage",
      desc: "A charming cottage in the 'Scotland of the East'. Enjoy the misty weather and beautiful waterfalls nearby.",
      img: {
        filename: "shillong_cottage",
        url: "https://images.unsplash.com/photo-1473643034988-c87e87b76041?auto=format&fit=crop&w=800&q=60",
      },
      price: 2200,
      location: "Shillong, Meghalaya",
      country: "India",
      category: "Mountains",
      geometry: { type: "Point", coordinates: [91.8933, 25.5788] },
    },
    {
      title: "Wooden Chalet in Gulmarg",
      desc: "Stay right on the ski slopes in this warm wooden chalet. Best experienced during the winter snow.",
      img: {
        filename: "gulmarg_chalet",
        url: "https://images.unsplash.com/photo-1518730518541-d0843268c287?auto=format&fit=crop&w=800&q=60",
      },
      price: 5000,
      location: "Gulmarg, Kashmir",
      country: "India",
      category: "Mountains",
      geometry: { type: "Point", coordinates: [74.3808, 34.0484] },
    },
    {
      title: "Ooty Tea Garden Home",
      desc: "A vintage bungalow surrounded by acres of tea plantations in the Nilgiris.",
      img: {
        filename: "ooty_home",
        url: "https://images.unsplash.com/photo-1544634076-a90160bcad7b?auto=format&fit=crop&w=800&q=60",
      },
      price: 3500,
      location: "Ooty, Tamil Nadu",
      country: "India",
      category: "Mountains",
      geometry: { type: "Point", coordinates: [76.6951, 11.4102] },
    },

    // --- AMAZING POOLS ---
    {
      title: "Infinity Pool Villa",
      desc: "Luxurious villa in Lonavala with a stunning infinity pool overlooking the Sahyadri mountains.",
      img: {
        filename: "lonavala_pool",
        url: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=800&q=60",
      },
      price: 8000,
      location: "Lonavala, Maharashtra",
      country: "India",
      category: "Amazing Pools",
      geometry: { type: "Point", coordinates: [73.4064, 18.7551] },
    },
    {
      title: "Private Plunge Pool Suite",
      desc: "Romantic suite with a private plunge pool, perfect for couples seeking privacy in Alibaug.",
      img: {
        filename: "alibaug_pool",
        url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=60",
      },
      price: 6500,
      location: "Alibaug, Maharashtra",
      country: "India",
      category: "Amazing Pools",
      geometry: { type: "Point", coordinates: [72.8722, 18.6414] },
    },
    {
      title: "Jungle Resort with Lagoon Pool",
      desc: "Stay in the heart of Jim Corbett National Park and relax in our massive lagoon-style swimming pool.",
      img: {
        filename: "corbett_pool",
        url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60",
      },
      price: 9000,
      location: "Jim Corbett, Uttarakhand",
      country: "India",
      category: "Amazing Pools",
      geometry: { type: "Point", coordinates: [79.1315, 29.53] },
    },

    // --- CAMPING ---
    {
      title: "Luxury Tent in Jaisalmer",
      desc: "Stay in the middle of the Thar Desert in a luxury tent. Enjoy camel safaris and folk dances by the bonfire.",
      img: {
        filename: "jaisalmer_tent",
        url: "https://images.unsplash.com/photo-1542823616-905c8794803d?auto=format&fit=crop&w=800&q=60",
      },
      price: 4000,
      location: "Jaisalmer, Rajasthan",
      country: "India",
      category: "Camping",
      geometry: { type: "Point", coordinates: [70.9083, 26.9157] },
    },
    {
      title: "Rishikesh Yoga Retreat",
      desc: "Find peace and balance at this riverside camp by the Ganga. Perfect for meditation and rafting.",
      img: {
        filename: "rishikesh_camp",
        url: "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=800&q=60",
      },
      price: 2000,
      location: "Rishikesh, Uttarakhand",
      country: "India",
      category: "Camping",
      geometry: { type: "Point", coordinates: [78.2676, 30.0869] },
    },
    {
      title: "Lakeside Camping Pawna",
      desc: "Sleep under the stars right next to Pawna Lake. BBQ, music, and bonfires included.",
      img: {
        filename: "pawna_camp",
        url: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=800&q=60",
      },
      price: 1500,
      location: "Lonavala, Maharashtra",
      country: "India",
      category: "Camping",
      geometry: { type: "Point", coordinates: [73.4965, 18.687] },
    },
    {
      title: "Spiti Valley Stargazing Camp",
      desc: "High-altitude camping experience in the cold desert of Spiti. Unmatched views of the Milky Way.",
      img: {
        filename: "spiti_camp",
        url: "https://images.unsplash.com/photo-1496545672479-7ac37b9698a7?auto=format&fit=crop&w=800&q=60",
      },
      price: 2500,
      location: "Spiti, Himachal Pradesh",
      country: "India",
      category: "Camping",
      geometry: { type: "Point", coordinates: [78.0059, 32.2276] },
    },

    // --- FARMS ---
    {
      title: "Coffee Estate Homestay",
      desc: "Wake up to the smell of fresh coffee beans. A serene homestay tucked away in the hills of Coorg.",
      img: {
        filename: "coorg_homestay",
        url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=60",
      },
      price: 2500,
      location: "Coorg, Karnataka",
      country: "India",
      category: "Farms",
      geometry: { type: "Point", coordinates: [75.7382, 12.3375] },
    },
    {
      title: "Organic Farm Stay Punjab",
      desc: "Experience rural Punjab life. Tractor rides, fresh milk, and mustard fields as far as the eye can see.",
      img: {
        filename: "punjab_farm",
        url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=60",
      },
      price: 2000,
      location: "Amritsar, Punjab",
      country: "India",
      category: "Farms",
      geometry: { type: "Point", coordinates: [74.8723, 31.634] },
    },
    {
      title: "Vineyard Stay Nashik",
      desc: "Stay in the wine capital of India. Tour the vineyards, taste premium wines, and relax in luxury.",
      img: {
        filename: "nashik_vineyard",
        url: "https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=800&q=60",
      },
      price: 6000,
      location: "Nashik, Maharashtra",
      country: "India",
      category: "Farms",
      geometry: { type: "Point", coordinates: [73.7898, 19.9975] },
    },
    {
      title: "Tea Garden Bungalow",
      desc: "Stay in the middle of lush green tea gardens. Wake up to the aroma of fresh tea and misty mountains.",
      img: {
        filename: "darjeeling_tea",
        url: "https://images.unsplash.com/photo-1544634076-a90160bcad7b?auto=format&fit=crop&w=800&q=60",
      },
      price: 3200,
      location: "Darjeeling, West Bengal",
      country: "India",
      category: "Farms",
      geometry: { type: "Point", coordinates: [88.2627, 27.036] },
    },

    // --- ARCTIC (Cold/Snow Destinations in India) ---
    {
      title: "Frozen River Trek Camp",
      desc: "Base camp for the famous Chadar Trek. Experience temperatures below -20°C in the heart of Ladakh.",
      img: {
        filename: "zanskar_frozen",
        url: "https://images.unsplash.com/photo-1518182170546-0766aa6f7a43?auto=format&fit=crop&w=800&q=60",
      },
      price: 4500,
      location: "Zanskar, Ladakh",
      country: "India",
      category: "Arctic",
      geometry: { type: "Point", coordinates: [76.8774, 33.9167] },
    },
    {
      title: "Snow Igloo Stay",
      desc: "India's first glass igloo stay in Sethan Valley. Surrounded by 5 feet of snow in winter.",
      img: {
        filename: "sethan_igloo",
        url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60",
      },
      price: 5000,
      location: "Sethan, Himachal Pradesh",
      country: "India",
      category: "Arctic",
      geometry: { type: "Point", coordinates: [77.1997, 32.227] },
    },
    {
      title: "Drass Valley Cold Stay",
      desc: "Stay in the second coldest inhabited place on earth. A true test of endurance and beauty.",
      img: {
        filename: "drass_valley",
        url: "https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?auto=format&fit=crop&w=800&q=60",
      },
      price: 2500,
      location: "Drass, Ladakh",
      country: "India",
      category: "Arctic",
      geometry: { type: "Point", coordinates: [75.7523, 34.4285] },
    },

    // --- DOMES ---
    {
      title: "Glamping Dome Jibhi",
      desc: "Futuristic geodesic dome stay in the forest of Jibhi. Great for stargazing from your bed.",
      img: {
        filename: "jibhi_dome",
        url: "https://images.unsplash.com/photo-1527010154944-f2241763d806?auto=format&fit=crop&w=800&q=60",
      },
      price: 4000,
      location: "Jibhi, Himachal Pradesh",
      country: "India",
      category: "Domes",
      geometry: { type: "Point", coordinates: [77.375, 31.6346] },
    },
    {
      title: "Kodaikanal Geodesic Dome",
      desc: "Luxury dome living with a view of the southern hills. Private deck and campfire included.",
      img: {
        filename: "kodai_dome",
        url: "https://images.unsplash.com/photo-1610444391694-82a6f23f03b2?auto=format&fit=crop&w=800&q=60",
      },
      price: 3500,
      location: "Kodaikanal, Tamil Nadu",
      country: "India",
      category: "Domes",
      geometry: { type: "Point", coordinates: [77.4892, 10.2381] },
    },
    {
      title: "Himalayan Dome Stay",
      desc: "Wake up to 360-degree views of the Himalayas in this luxury glamping dome in Manali.",
      img: {
        filename: "manali_dome",
        url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
      },
      price: 5500,
      location: "Manali, Himachal Pradesh",
      country: "India",
      category: "Domes",
      geometry: { type: "Point", coordinates: [77.1892, 32.2396] },
    },

    // --- BOATS ---
    {
      title: "Backwater Houseboat Stay",
      desc: "Float along the serene backwaters of Kerala in a traditional houseboat. Enjoy freshly caught fish and witness breathtaking sunsets.",
      img: {
        filename: "kerala_houseboat",
        url: "https://images.unsplash.com/photo-1593693397690-362cb9666c74?auto=format&fit=crop&w=800&q=60",
      },
      price: 3500,
      location: "Alleppey, Kerala",
      country: "India",
      category: "Boats",
      geometry: { type: "Point", coordinates: [76.3388, 9.4981] },
    },
    {
      title: "Dal Lake Shikara Stay",
      desc: "Experience the magic of Kashmir by staying on a stationary Shikara boat on the Dal Lake.",
      img: {
        filename: "srinagar_boat",
        url: "https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=60",
      },
      price: 3000,
      location: "Srinagar, Kashmir",
      country: "India",
      category: "Boats",
      geometry: { type: "Point", coordinates: [74.8365, 34.0937] },
    },
    {
      title: "Luxury Yacht Stay Goa",
      desc: "Rent a private yacht for the night in the Mandovi river. Butler service and champagne breakfast included.",
      img: {
        filename: "goa_yacht",
        url: "https://images.unsplash.com/photo-1605281317010-fe5ffe79ba02?auto=format&fit=crop&w=800&q=60",
      },
      price: 15000,
      location: "Panjim, Goa",
      country: "India",
      category: "Boats",
      geometry: { type: "Point", coordinates: [73.8327, 15.4909] },
    },
    {
      title: "Ganges River Cruise",
      desc: "A boutique cruise stay moving from Varanasi to Patna. Explore historical sites along the river.",
      img: {
        filename: "ganges_boat",
        url: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=60",
      },
      price: 12000,
      location: "Varanasi, Uttar Pradesh",
      country: "India",
      category: "Boats",
      geometry: { type: "Point", coordinates: [83.0076, 25.3176] },
    },
  ],
};

module.exports = sampleListings;
